const LOGIN = 'login/LOGIN'
const LOGIN_SUCCESS = 'login/LOGIN_SUCCESS'
const LOGIN_FAILURE = 'login/LOGIN_FAILURE'
const LOGOUT = 'login/LOGOUT';
const LOGOUT_SUCCESS = 'login/LOGOUT_SUCCESS';
const LOGOUT_FAILURE = 'login/LOGOUT_FAILURE';
const REGISTER = 'login/REGISTER';
const REGISTER_SUCCESS = 'login/REGISTER_SUCCESS';
const REGISTER_FAILURE = 'login/REGISTER_FAILURE';
const FORGOTTEN_PASSWORD = 'login/FORGOTTEN_PASSWORD'
const FORGOTTEN_PASSWORD_SUCCESS = 'login/FORGOTTEN_PASSWORD_SUCCESS'
const FORGOTTEN_PASSWORD_FAILURE = 'login/FORGOTTEN_PASSWORD_FAILURE'

export default {
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    LOGOUT_SUCCESS,
    LOGOUT_FAILURE,
    REGISTER,
    REGISTER_SUCCESS,
    REGISTER_FAILURE,
    FORGOTTEN_PASSWORD,
    FORGOTTEN_PASSWORD_SUCCESS,
    FORGOTTEN_PASSWORD_FAILURE
}