const LOAD_BOOKS = 'book/LOAD_BOOKS'
const LOAD_BOOKS_SUCCESS = 'book/LOAD_BOOKS_SUCCESS'
const LOAD_BOOKS_FALIURE = 'book/LOAD_BOOKS_FALIURE'
const SET_FILTER = 'book/SET_FILTER'

export default {
    LOAD_BOOKS,
    LOAD_BOOKS_SUCCESS,
    LOAD_BOOKS_FALIURE,
    SET_FILTER
}